"use client";

import { useForm, useWatch } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Tag } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { BaseAdminDialog } from "../base-admin-dialog";
import {
  attributeOptionSchema,
  slugify,
  type AttributeOptionInput,
} from "../../_schemas/category-admin.schema";

interface CreateAttributeOptionDialogProps {
  attributeId: string;
}

export function CreateAttributeOptionDialog({
  attributeId,
}: CreateAttributeOptionDialogProps) {
  const utils = trpc.useUtils();
  const form = useForm<AttributeOptionInput>({
    resolver: zodResolver(attributeOptionSchema),
    defaultValues: { label: "", value: "" },
  });

  const watchedLabel = useWatch({ control: form.control, name: "label" });

  const mutation = trpc.admin.createAttributeOption.useMutation({
    onSuccess: () => {
      toast.success("Opsi atribut berhasil ditambahkan");
      utils.admin.getCategoryTree.invalidate();
    },
    onError: (err) => toast.error(err.message || "Gagal menambah opsi atribut"),
  });

  return (
    <BaseAdminDialog
      trigger={
        <Button
          size="sm"
          variant="ghost"
          className="h-6 px-2 text-[11px] gap-1 font-medium"
        >
          <Tag className="h-3 w-3 text-muted-foreground" />
          <span>Tambah Opsi</span>
        </Button>
      }
      title="Tambah Opsi Atribut"
      form={form}
      onSubmit={(data) =>
        mutation.mutate({
          attributeId,
          label: data.label,
          value: data.value || slugify(data.label),
        })
      }
      isPending={mutation.isPending}
      submitText="Simpan Opsi"
      submitIcon={null}
    >
      <FormField
        control={form.control}
        name="label"
        render={({ field }) => (
          <FormItem>
            <FormLabel className="text-xs font-bold uppercase text-muted-foreground">
              Label Opsi
            </FormLabel>
            <FormControl>
              <Input placeholder="e.g., TypeScript, Minimalist" {...field} />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <FormField
        control={form.control}
        name="value"
        render={({ field }) => (
          <FormItem>
            <FormLabel className="text-xs font-bold uppercase text-muted-foreground">
              Value System (Autogenerated jika kosong)
            </FormLabel>
            <FormControl>
              <Input
                placeholder={
                  watchedLabel ? slugify(watchedLabel) : "e.g., typescript"
                }
                {...field}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />
    </BaseAdminDialog>
  );
}
